### ISSUE TITLE
[FIX] 공구폼 수정시 value값 넣기, 공구열기 주소 수정

### ISSUE THREAD

**Issue by nayujin-dev** [Co-buying/cwave_beta#63]
## 설명

- 공구폼 수정시 value값 넣기
- 공구열기 주소 수정

## ToDo

- [x] 공구 열기 path 수정
- [x] 공구폼 수정시 value에 detailObj 연결
- [x] 카카오로 링크타고 들어올시 인터넷으로 연결하게 안내
